export const theme = {
  title: 'light',
  colors: {
    text: '#000000',
    background: '#ffffff',
    buttonText: '#ffffff',
    border: ' #E8E8E8',
    linear: 'linear-gradient(90deg, #00FFFF 0%, #7000FF 109.38%)',
    especial: '#21B5FF',
    especialPlus: '#0061ff',
    borderEspecial: '#CCDFFF',
    switchColor: '#ffbf71',
    shadow: 'rgb(0 0 0 / 10%)',
  },
  spacings: {
    extraSmall: '0.5rem',
    small: '1rem',
    medium: '2rem',
    large: '3rem',
    superLarge: '4rem',
    bigLarge: '20rem',
    container: '80rem',
    containerLarge: '96rem',
  },
  font: {
    sizes: {
      small: '1.4rem',
      medium: '1.8rem',
      large: '2.2rem',
      superLarge: '4.8rem',
    },
  },
};
export const darkTheme = {
  title: 'dark',
  colors: {
    text: '#C9D1D9',
    background: '#02001A',
    border: ' #E8E8E8',
    buttonText: '#ffffff',
    linear: 'linear-gradient(90deg, #00FFFF 0%, #7000FF 109.38%)',
    especial: '#21B5FF',
    especialPlus: '#0061ff',
    borderEspecial: '#CCDFFF',
    switchColor: '#d9fbff',
    shadow: 'rgb(255 248 248 / 10%)',
  },
  spacings: {
    extraSmall: '0.5rem',
    small: '1rem',
    medium: '2rem',
    large: '3rem',
    superLarge: '4rem',
    bigLarge: '20rem',
    container: '80rem',
    containerLarge: '96rem',
  },
  font: {
    sizes: {
      small: '1.4rem',
      medium: '1.8rem',
      large: '2.2rem',
      superLarge: '4.8rem',
    },
  },
};
